apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secret
type: Opaque
stringData:
  SMTP_HOST: smtp.gmail.com
  SMTP_PORT: "587"
  SMTP_USER: notify@example.com
  SMTP_PASS: changeme
  KAFKA_BROKER: kafka:9092
